loglevel: info
cpus: 1
monitoring:
  port: 5555
ssl:
  cert: "./certs/server.cert"
  key: "./certs/server.key"
  root_cert: "./certs/root.cert"
protocols:
  http:
    enable: true
    mocks_dir: "./mocks"
    port: 8080
  https:
    enable: false
    port: 8443
  http2:
    enable: false
    port: 8081
  ws:
    enable: false
    mocks_dir: "./ws_mocks"
    port: 8082
  grpc:
    enable: false
    host: localhost
    port: 4312
    mocks_dir: "./grpc/mocks"
    protos_dir: "./grpc/protos"
    grpc_tls: false
  thrift:
    enable: false
    mocks_dir: "./thrift/mocks"
    services:
      - port: 9999
        service: "/opt/gen-nodejs/Calculator"
        handlers:
          - add
          - substract
          - ping
backup:
  enable: false
  cron: "0 * * * *" # Hourly Backup
cache:
  enable: false
  ttl_seconds: 300
injection:
  enable: false
origins:
  - http://localhost:3000/
  - http://localhost:3001/
  - http://localhost:5000/
# ext_helpers: "./custom_handlebar.json"
# ext_data_source:
#   pg:
#     host: localhost
#     port: 5432
#     user: root
#     password: password
#     database: postgres
