site_name: Camouflage
site_author: Shubhendu Madhukar
repo_url: https://github.com/fauxauldrich/camouflage
theme:
  name: material
  logo: camouflage.png
  features:
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: red
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - admonition
  - attr_list
nav:
  - index.md
  - getting-started.md
  - folder-structure.md
  - handlebars.md
  - request-matching.md
  - default-response.md
  - custom-handlebars.md
  - request-model.md
  - response-delays.md
  - performance-mode.md
  - mocking-gRPC.md
  - mocking-websockets.md
  - camouflage-ui.md
  - available-monitoring.md
  - tests.md
  - back-up-and-restore.md
  - openAPI-conversion.md
  - contributing.md
extra:
  logo: "camouflage.svg"
